/*
 * CinemaReservation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The CreateAccountDto model module.
 * @module model/CreateAccountDto
 * @version 1.0
 */
export class CreateAccountDto {
  /**
   * Constructs a new <code>CreateAccountDto</code>.
   * @alias module:model/CreateAccountDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CreateAccountDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateAccountDto} obj Optional instance to populate.
   * @return {module:model/CreateAccountDto} The populated <code>CreateAccountDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateAccountDto();
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} email
 */
CreateAccountDto.prototype.email = undefined;

/**
 * @member {String} password
 */
CreateAccountDto.prototype.password = undefined;

/**
 * @member {String} name
 */
CreateAccountDto.prototype.name = undefined;

