/*
 * CinemaReservation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The CreateShowingDto model module.
 * @module model/CreateShowingDto
 * @version 1.0
 */
export class CreateShowingDto {
  /**
   * Constructs a new <code>CreateShowingDto</code>.
   * @alias module:model/CreateShowingDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CreateShowingDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateShowingDto} obj Optional instance to populate.
   * @return {module:model/CreateShowingDto} The populated <code>CreateShowingDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateShowingDto();
      if (data.hasOwnProperty('date'))
        obj._date = ApiClient.convertToType(data['date'], 'Date');
      if (data.hasOwnProperty('movieId'))
        obj.movieId = ApiClient.convertToType(data['movieId'], 'Number');
      if (data.hasOwnProperty('hallId'))
        obj.hallId = ApiClient.convertToType(data['hallId'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Date} _date
 */
CreateShowingDto.prototype._date = undefined;

/**
 * @member {Number} movieId
 */
CreateShowingDto.prototype.movieId = undefined;

/**
 * @member {Number} hallId
 */
CreateShowingDto.prototype.hallId = undefined;

