/*
 * CinemaReservation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The DateTimeInt32ValueTuple model module.
 * @module model/DateTimeInt32ValueTuple
 * @version 1.0
 */
export class DateTimeInt32ValueTuple {
  /**
   * Constructs a new <code>DateTimeInt32ValueTuple</code>.
   * @alias module:model/DateTimeInt32ValueTuple
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DateTimeInt32ValueTuple</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DateTimeInt32ValueTuple} obj Optional instance to populate.
   * @return {module:model/DateTimeInt32ValueTuple} The populated <code>DateTimeInt32ValueTuple</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DateTimeInt32ValueTuple();
      if (data.hasOwnProperty('item1'))
        obj.item1 = ApiClient.convertToType(data['item1'], 'Date');
      if (data.hasOwnProperty('item2'))
        obj.item2 = ApiClient.convertToType(data['item2'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Date} item1
 */
DateTimeInt32ValueTuple.prototype.item1 = undefined;

/**
 * @member {Number} item2
 */
DateTimeInt32ValueTuple.prototype.item2 = undefined;

