/*
 * CinemaReservation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The HallDto model module.
 * @module model/HallDto
 * @version 1.0
 */
export class HallDto {
  /**
   * Constructs a new <code>HallDto</code>.
   * @alias module:model/HallDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>HallDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HallDto} obj Optional instance to populate.
   * @return {module:model/HallDto} The populated <code>HallDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new HallDto();
      if (data.hasOwnProperty('hallId'))
        obj.hallId = ApiClient.convertToType(data['hallId'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('rows'))
        obj.rows = ApiClient.convertToType(data['rows'], 'Number');
      if (data.hasOwnProperty('columns'))
        obj.columns = ApiClient.convertToType(data['columns'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} hallId
 */
HallDto.prototype.hallId = undefined;

/**
 * @member {String} name
 */
HallDto.prototype.name = undefined;

/**
 * @member {Number} rows
 */
HallDto.prototype.rows = undefined;

/**
 * @member {Number} columns
 */
HallDto.prototype.columns = undefined;

